apiVersion: apps/v1
kind: Deployment
metadata:
  name: sandbox
  namespace: default
spec:
  selector:
    matchLabels:
      name: sandbox
  replicas: 1
  template:
    metadata:
      labels:
        name: sandbox
    spec:
      containers:
      - name: sandbox
        image: ghcr.io/nikitavbv/sandbox/sandbox:0.1.299
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
        - name: SANDBOX_CONFIG_PATH
          value: /etc/sandbox/config/config.toml
        volumeMounts:
        - name: config
          mountPath: /etc/sandbox/config
      volumes:
      - name: config
        configMap:
          name: sandbox-config
          items:
          - key: config.toml
            path: config.toml
---
apiVersion: v1
kind: Service
metadata:
  name: sandbox
  namespace: default
spec:
  selector:
    name: sandbox
  ports:
  - name: 'http'
    port: 80
    targetPort: 8080
  - name: 'grpc'
    port: 8081
    targetPort: 8082
