on: [push]

name: Continuous integration

jobs:
  server-build:
    name: Server Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
    - uses: Swatinem/rust-cache@v2
    - uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        if ! command -v sqlx &> /dev/null
        then
          cargo install sqlx-cli
        fi
    - run: sqlx migrate run
      env:
        DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --release
      env:
        DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: -p sandbox-server --release
      env:
        DATABASE_URL: "postgres://postgres:postgres@localhost:5432/postgres"
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        file: infrastructure/docker/server.Dockerfile
        context: '.'
        push: true
        tags: |
          ghcr.io/nikitavbv/sandbox/sandbox:latest
          ghcr.io/nikitavbv/sandbox/sandbox:0.1.${{ github.run_number }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - uses: actions/upload-artifact@v3
      with:
        name: release-build
        path: target/release/sandbox-server

  ui-build:
    name: UI Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/bin
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ui/target/
        key: ${{ runner.os }}-cargo-ui-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-ui-build-
    - uses: arduino/setup-protoc@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        target: wasm32-unknown-unknown
    - run: |
        if ! command -v trunk &> /dev/null
        then
          cargo install trunk
        fi
    - run: trunk build --release
      working-directory: ui
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/build-push-action@v4
      with:
        file: infrastructure/docker/web.Dockerfile
        context: '.'
        push: true
        tags: |
          ghcr.io/nikitavbv/sandbox/sandbox-ui:latest
          ghcr.io/nikitavbv/sandbox/sandbox-ui:0.1.${{ github.run_number }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
